import { mkdirSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, normalize, sep } from 'node:path';

/**
 * Production "work folder" — where the user keeps raw footage, edit projects,
 * drafts, and per-platform finals during a production. Distinct from
 * `data/files/output/` (which is the publish-ready export generated by
 * `generateOutputFolder`). Derived purely from the production slug so no
 * extra DB column is needed.
 *
 * Layout:
 *   data/files/productions/<slug>/
 *     nagrywanie/  ← raw, audio, bts
 *       raw/
 *       audio/
 *       bts/
 *     obrobka/     ← project files, drafts, third-party assets
 *       project/
 *       drafts/
 *       assets/
 *     publikacja/  ← per-platform finals + cover + captions copy
 */

const ROOT = () => join(process.cwd(), 'data', 'files', 'productions');

export const WORK_STAGES = ['nagrywanie', 'obrobka', 'publikacja'] as const;
export type WorkStage = (typeof WORK_STAGES)[number];

const STAGE_LAYOUT: Record<WorkStage, string[]> = {
  nagrywanie: ['raw', 'audio', 'bts'],
  obrobka: ['project', 'drafts', 'assets'],
  publikacja: [],
};

function safeSlug(slug: string): string {
  const s = slug
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-zA-Z0-9._-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase()
    .slice(0, 120);
  if (!s) throw new Error(`Invalid production slug: "${slug}"`);
  return s;
}

/** Absolute path to the production's work folder root. Does NOT create it. */
export function getWorkFolderRoot(slug: string): string {
  return join(ROOT(), safeSlug(slug));
}

/** Absolute path to a specific stage subfolder. Does NOT create it. */
export function getWorkStagePath(slug: string, stage: WorkStage): string {
  return join(getWorkFolderRoot(slug), stage);
}

/**
 * Idempotently create the full stage subfolder layout for a production.
 * Safe to call repeatedly (existing folders are skipped).
 */
export function ensureWorkFolderStructure(slug: string): string {
  const root = getWorkFolderRoot(slug);
  if (!existsSync(root)) mkdirSync(root, { recursive: true });
  for (const stage of WORK_STAGES) {
    const stagePath = join(root, stage);
    if (!existsSync(stagePath)) mkdirSync(stagePath, { recursive: true });
    for (const sub of STAGE_LAYOUT[stage]) {
      const subPath = join(stagePath, sub);
      if (!existsSync(subPath)) mkdirSync(subPath, { recursive: true });
    }
  }
  return root;
}

export type WorkStageStats = {
  stage: WorkStage;
  fileCount: number;
};

/** Count files (recursively) inside each stage subfolder. */
export function countWorkFolderFiles(slug: string): WorkStageStats[] {
  const root = getWorkFolderRoot(slug);
  if (!existsSync(root)) return WORK_STAGES.map((stage) => ({ stage, fileCount: 0 }));
  return WORK_STAGES.map((stage) => ({ stage, fileCount: countFilesRecursive(join(root, stage)) }));
}

function countFilesRecursive(dir: string): number {
  if (!existsSync(dir)) return 0;
  let count = 0;
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    try {
      const s = statSync(full);
      if (s.isDirectory()) count += countFilesRecursive(full);
      else if (s.isFile()) count += 1;
    } catch {
      /* skip unreadable entries */
    }
  }
  return count;
}

/**
 * Resolve a stage path with path-traversal guard. Throws if the resolved
 * absolute path would escape the work folder root. Returned path is
 * guaranteed to live under `data/files/productions/<slug>/<stage>/`.
 */
export function resolveSafeStagePath(slug: string, stage: WorkStage): string {
  const root = getWorkFolderRoot(slug);
  const stagePath = normalize(join(root, stage));
  if (!stagePath.startsWith(root + sep) && stagePath !== root) {
    throw new Error('Path traversal detected');
  }
  return stagePath;
}
